# Generated by Django 2.2.16 on 2022-08-27 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_comment_review_user'),
        ('reviews', '0002_auto_20220825_2259'),
    ]

    operations = [
    ]
